[log]
log_filename = "./logs/testlog.log"
log_file_maxsize = 100
log_time_key = "Time"
log_level_key = "Level"
log_name_key = "Logger"
log_caller_key = "Caller"
log_message_key = "Message"
stacktrace_key = "Stracktrace"
log_level = "Debug"
stacktrace_level = "Error"
service_name = "log_zap_demo"
